spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/postgres/ZuzexApp
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver


   flyway:
      schemas: ZuzexApp
      baseline-on-migrate: true
   jpa:
      show-sql: true

   sql:
      init:
         mode: always
         continue-on-error: false

   security:
      jwt:
         secret: jwtPass
         access: 3600000
         refresh: 2592000000


